### ISSUE TITLE
Master Altimor.

### ISSUE THREAD

**Issue by secretstation** [AltimorTASDK/TribesXT#1]
I'm terribly sorry that I dared to be so arrogant. But can I get a discord to contact you. A big debate broke out in the Russian forum on the topic(https://yougame.biz/threads/314699/#post-3062421) of your protection, where people claim that they were able to crack your code, while knowledgeable people have been defending you and since 2018 prove that a crack is impossible. I would like to ask a couple of questions in the discord and find out from you personally if they were able to crack the cheat.

_- Sincerely a fan of your lightweight x86 interpreter._

**Comment by AltimorTASDK** [comment]
I don't develop skeetcheat. I'm just friends with eso/skeet, and people have wild imaginations apparently.

The x86 interpreter is actually the one thing in this repo I didn't write. NoFiX is the name of the author.
